title: "Trịnh Quang Lâm"
author: "Trịnh Quang Lâm"
description: "" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "trinhquanglam2k4@gmail.com"
# twitter_username: "twitteruser"
github_username: "https://github.com/quanglam04"
linkedin_username: "https://www.linkedin.com/in/quanglam04/"
facebook_username: https://www.facebook.com/profile.php?id=100041721947314
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"
paginate: 5 # số bài viết mỗi trang
paginate_path: "/page:num" # URL của các trang phân trang
rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
